(in-package #:cl-user)
(defpackage #:scgs)
(in-package #:scgs)


(defvar *lang-context* "base-")
(defvar *time-context* "base-")
(defvar *kids-context* "base-")
(defvar *guidedTour-context* "base-")
(defvar *freeVisit-context* "base-")
(defvar *connection-context* "base-")
(defvar *color-context* "base-")
(defvar *memory-context* "base-")
(defvar *battery-context* "base-")
(defvar *kidslang-context* "base-")