/*
ContextInitializer.m
Autogenerated by Subjective-C compiler.
*/

#import "CacheManager.h"
#import "CacheManager_LANGUAGE.h"
#import "CacheManager_PREFEREDPOIS.h"
#import "CategoryPoi.h"
#import "CategoryPoi_LANGUAGE.h"
#import "ContextsManager.h"
#import "ContextsViewController.h"
#import "DemoGuideAppDelegate.h"
#import "Description.h"
#import "Description_LANGUAGE.h"
#import "DescViewController.h"
#import "DescViewController_COLOR.h"
#import "FreeVisitMapViewController.h"
#import "FreeVisitMapViewController_COLOR.h"
#import "GuidedVisitMapController.h"
#import "GuidedVisitMapController_GUIDEDTOUR.h"
#import "Itinerary.h"
#import "Itinerary_LANGUAGE.h"
#import "MenuViewController.h"
#import "MKAnnotation.h"
#import "Poi.h"
#import "Poi_LANGUAGE.h"
#import "Poi_TIME.h"
#import "POIViewController.h"
#import "POIViewController_CATEGORY.h"
#import "POiViewController_ITINERARY.h"
#import "POIViewController_KID.h"
#import "POIViewController_LANGUAGE.h"
#import "POIViewController_TIME.h"
#import "Reachability.h"
#import "Schedule.h"
#import "ScheduleDay.h"
#import "SQLManager.h"
#import "ToolsCategoriesViewController.h"
#import "ToolsCategoriesViewController_COLOR.h"
#import "ToolsLangViewController.h"
#import "ToolsViewController.h"
#import "ToolsViewController_UPDATE.h"
#import "Town.h"
#import "UpdateAlertViewController.h"
#import "ContextsInitializer.h"


@implementation ContextsInitializer

- (void)initializeContexts {
    @synchronized([self class]) {
        if (alreadyInitialized) {
            return;
        }
        alreadyInitialized = YES;
    }
    // Contexts initialization
    SCContext *__French = [[SCGlobalContext alloc] initWithName:@"French"]; 
[[SCContextManager sharedContextManager] addContext:__French]; 
SCContext *__English = [[SCGlobalContext alloc] initWithName:@"English"]; 
[[SCContextManager sharedContextManager] addContext:__English]; 
SCContext *__Dutch = [[SCGlobalContext alloc] initWithName:@"Dutch"]; 
[[SCContextManager sharedContextManager] addContext:__Dutch]; 
SCContext *__DbUpdate = [[SCGlobalContext alloc] initWithName:@"DbUpdate"]; 
[[SCContextManager sharedContextManager] addContext:__DbUpdate]; 
SCContext *__LowMemory = [[SCGlobalContext alloc] initWithName:@"LowMemory"]; 
[[SCContextManager sharedContextManager] addContext:__LowMemory]; 
SCContext *__LowBattery = [[SCGlobalContext alloc] initWithName:@"LowBattery"]; 
[[SCContextManager sharedContextManager] addContext:__LowBattery]; 
SCContext *__SimpleInterface = [[SCGlobalContext alloc] initWithName:@"SimpleInterface"]; 
[[SCContextManager sharedContextManager] addContext:__SimpleInterface]; 
SCContext *__TimeAdaptation = [[SCGlobalContext alloc] initWithName:@"TimeAdaptation"]; 
[[SCContextManager sharedContextManager] addContext:__TimeAdaptation]; 
SCContext *__GPS = [[SCGlobalContext alloc] initWithName:@"GPS"]; 
[[SCContextManager sharedContextManager] addContext:__GPS]; 
SCContext *__CategoryPoiOrder = [[SCGlobalContext alloc] initWithName:@"CategoryPoiOrder"]; 
[[SCContextManager sharedContextManager] addContext:__CategoryPoiOrder]; 
SCContext *__ItineraryPoiOrder = [[SCGlobalContext alloc] initWithName:@"ItineraryPoiOrder"]; 
[[SCContextManager sharedContextManager] addContext:__ItineraryPoiOrder]; 
SCContext *__PreferedPois = [[SCGlobalContext alloc] initWithName:@"PreferedPois"]; 
[[SCContextManager sharedContextManager] addContext:__PreferedPois]; 
SCContext *__GuidedTour = [[SCGlobalContext alloc] initWithName:@"GuidedTour"]; 
[[SCContextManager sharedContextManager] addContext:__GuidedTour]; 
SCContext *__RefreshPoiMap = [[SCGlobalContext alloc] initWithName:@"RefreshPoiMap"]; 
[[SCContextManager sharedContextManager] addContext:__RefreshPoiMap]; 
SCContext *__ColoredCategories = [[SCGlobalContext alloc] initWithName:@"ColoredCategories"]; 
[[SCContextManager sharedContextManager] addContext:__ColoredCategories]; 
SCContext *__Connected = [[SCGlobalContext alloc] initWithName:@"Connected"]; 
[[SCContextManager sharedContextManager] addContext:__Connected]; 
SCContext *__ConnectedWifi = [[SCGlobalContext alloc] initWithName:@"ConnectedWifi"]; 
[[SCContextManager sharedContextManager] addContext:__ConnectedWifi]; 
SCContext *__Connected3G = [[SCGlobalContext alloc] initWithName:@"Connected3G"]; 
[[SCContextManager sharedContextManager] addContext:__Connected3G]; 
SCContext *__Morning = [[SCGlobalContext alloc] initWithName:@"Morning"]; 
[[SCContextManager sharedContextManager] addContext:__Morning]; 
SCContext *__Afternoon = [[SCGlobalContext alloc] initWithName:@"Afternoon"]; 
[[SCContextManager sharedContextManager] addContext:__Afternoon]; 
SCContext *__Evening = [[SCGlobalContext alloc] initWithName:@"Evening"]; 
[[SCContextManager sharedContextManager] addContext:__Evening]; 
[__ItineraryPoiOrder addExclusionLinkWithContext:__CategoryPoiOrder];
[__French addExclusionLinkWithContext:__English];
[__French addExclusionLinkWithContext:__Dutch];
[__English addExclusionLinkWithContext:__French];
[__English addExclusionLinkWithContext:__Dutch];
[__Dutch addExclusionLinkWithContext:__French];
[__Dutch addExclusionLinkWithContext:__English];
[__Morning addExclusionLinkWithContext:__Afternoon];
[__Morning addExclusionLinkWithContext:__Evening];
[__Afternoon addExclusionLinkWithContext:__Morning];
[__Afternoon addExclusionLinkWithContext:__Evening];
[__Evening addExclusionLinkWithContext:__Afternoon];
[__Evening addExclusionLinkWithContext:__Morning];
[__ConnectedWifi addHardInclusionLinkWithContext:__Connected];
[__Connected3G addHardInclusionLinkWithContext:__Connected];
[__ItineraryPoiOrder addRequiresLinkWithContext:__GuidedTour];

    // Context methods registration
}

@end