/*
ContextInitializer.m
Autogenerated by Subjective-C compiler.
*/

#import <Foundation/Foundation.h> 

@interface ContextsInitializer : NSObject {
    BOOL alreadyInitialized;
}

- (void)initializeContexts; 

@end