(in-package #:cl-user)
(defpackage #:scg (:use #:amos-cl))
(in-package #:scg)

(defcontext @english)
(defcontext @french)
(defcontext @dutch)
(defcontext @morning)
(defcontext @afternoon)
(defcontext @night)
(defcontext @guided-tour)
(defcontext @free-visit)